# ==========================
# PREDICTIVE MAINTENANCE CONFIG
# ==========================

data:
  train_path: "data/CMaps/train_FD001.txt"
  test_path:  "data/CMaps/test_FD001.txt"
  rul_path:   "data/CMaps/RUL_FD001.txt"
  max_rul: 125             # cap for RUL values
  window_size: 30          # sequence length for LSTM

model:
  architecture: "LSTM"
  input_dim: null           # automatically inferred after feature selection
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  output_dim: 1

training:
  batch_size: 64
  epochs: 60
  patience: 10              # early stopping patience

  lr: 0.001
  alpha: 0.8               # for weighted loss function

system:
  seed: 42
  device: "cuda"

preprocessing:
  scaling: "standard"       # StandardScaler
  feature_engineering: true # add engineered features like avg_temp, mech_energy
