system:
  seed: 42
  device: "cuda"          # options: "cuda" or "cpu"
  num_workers: 2

model:
  architecture: "efficientnet_b0"
  num_classes: 2
  pretrained: true

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 20
  patience: 3
  image_size: 300

transforms:
  resize: [224, 224]
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

paths:
  data_dir: "./data"
  train_csv: "./data/train/_classes.csv"
  valid_csv: "./data/valid/_classes.csv"
  train_images: "./data/train"
  valid_images: "./data/valid"
  models_dir: "./models"
  results_dir: "./results"
  best_model: "./models/best_model.pth"